# Generated by Django 6.0.6 on 2026-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrption', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_livraison', models.CharField(max_length=30)),
                ('date_livraison', models.DateField()),
                ('observation', models.TextField()),
                ('produit', models.ManyToManyField(to='magasin.produit')),
            ],
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=30)),
                ('fournisseur', models.CharField(max_length=100)),
                ('date_commande', models.DateField()),
                ('statut', models.CharField(choices=[('en attente', 'en attente'), ('validée', 'validée'), ('livrée', 'livrée')], max_length=20)),
                ('produits', models.ManyToManyField(to='magasin.produit')),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vente', models.CharField(max_length=30)),
                ('date_vente', models.DateField()),
                ('nom_client', models.CharField(max_length=100)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('produits', models.ManyToManyField(to='magasin.produit')),
            ],
        ),
    ]
