# Generated by Django 6.0.6 on 2026-07-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='descrption',
            new_name='description',
        ),
    ]
